apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: issm-mec-cnmp-api
rules:
- apiGroups:
  - "argoproj.io"
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: issm-mec-cnmp-api
  namespace: 5g-core
subjects:
- kind: ServiceAccount
  name: default
  namespace: 5g-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: issm-mec-cnmp-api
