apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: issm-mec-cnmp-api
  namespace: 5g-core
rules:
- apiGroups:
  - "argoproj.io"
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: issm-mec-cnmp-api
  namespace: 5g-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: issm-mec-cnmp-api
subjects:
- kind: ServiceAccount
  name: default
  namespace: 5g-core
- kind: Group
  name: system:serviceaccounts:default
  apiGroup: rbac.authorization.k8s.io
  namespace: 5g-core
