apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-server
  name: api-server
spec:
  ports:
  - port: 8080
    name: http-api
    nodePort: 30055
  selector:
    app: api-server
  type: NodePort
