apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fiveg-subnet-010203-topology-
spec:
  entrypoint: handlerequest
  arguments:
    parameters:
    - name: issm_mec_cnmp_url
      value: http://172.15.0.200:30055
    - name: cluster-150-network-spec
      value: |
        [
          {
              "name": "sbi", "master": "ens160", "range": "10.100.200.0/24",
              "start": "10.100.200.2", "end": "10.100.200.20"
          },
          {
              "name": "up", "master": "ens160", "range": "172.15.0.0/24",
              "start": "172.15.0.4", "end": "172.15.0.10"        
          }
        ] 
    - name: cluster-240-network-spec
      value: |
        [
          {
              "name": "sbi", "master": "ens160", "range": "10.100.200.0/24",
              "start": "10.100.200.21", "end": "10.100.200.40"
          },
          {
              "name": "up", "master": "ens160", "range": "172.15.0.0/24",
              "start": "172.15.0.11", "end": "172.15.0.20"        
          }
        ] 
    - name: cluster-245-network-spec
      value: |
        [
          {
              "name": "sbi", "master": "ens160", "range": "10.100.200.0/24",
              "start": "10.100.200.41", "end": "10.100.200.60"
          },
          {
              "name": "up", "master": "ens160", "range": "172.15.0.0/24",
              "start": "172.15.0.21", "end": "172.15.0.30"        
          }
        ] 
      

  templates:
  - name: handlerequest
    dag:
      tasks:
      - name: subnet-A-branch
        # IMPORTANT: ensure correct network spec is passed to this cluster
        # i.e. cluster-240-network-spec
        template: create-subnet
        arguments:
          parameters:
          - name: data
            value: |
              { "cluster": "cluster-150",
                "cluster_core": "cluster-150",
                "namespace": "{{workflow.namespace}}",
                "smf_name": "smf-sample",
                "core_namespace": "domain-operator-a",
                "sst": "1",
                "sd": "010203",
                "connectedFrom": "gNB",
                "networks": {{workflow.parameters.cluster-150-network-spec}}
              }

      - name: subnet-B-anchor
        # IMPORTANT: ensure correct network spec is passed to this cluster
        # i.e. cluster-240-network-spec
        template: create-subnet
        dependencies: [subnet-A-branch]
        arguments:
          parameters:
          - name: data
            value: |
              { "cluster": "cluster-240",
                "cluster_core": "cluster-150",
                "namespace": "{{workflow.namespace}}",
                "smf_name": "smf-sample",
                "core_namespace": "domain-operator-a",
                "sst": "1",
                "sd": "010203",
                "pool": "60.61.0.0/16",
                "connectedFrom": "{{tasks.subnet-A-branch.outputs.parameters.fiveg_subnet_id}}",
                "networks": {{workflow.parameters.cluster-240-network-spec}}
              }

      - name: subnet-C-anchor
        # IMPORTANT: ensure correct network spec is passed to this cluster
        # i.e. cluster-245-network-spec
        template: create-subnet
        dependencies: [subnet-A-branch]
        arguments:
          parameters:
          - name: data
            value: |
              { "cluster": "cluster-245",
                "cluster_core": "cluster-150",
                "namespace": "{{workflow.namespace}}",
                "smf_name": "smf-sample",
                "core_namespace": "domain-operator-a",
                "sst": "1",
                "sd": "010203",
                "pool": "60.62.0.0/16",
                "connectedFrom": "{{tasks.subnet-A-branch.outputs.parameters.fiveg_subnet_id}}",
                "networks": {{workflow.parameters.cluster-245-network-spec}}
              }

  - name: create-subnet
    inputs:
      parameters:
      - name: data
    script:
      image: docker.pkg.github.com/5gzorro/issm/python:alpine3.6-kafka-v0.1
      imagePullPolicy: IfNotPresent
      command: [python]
      source: |
        import json
        import re
        import requests
        import sys

        headers = {'Content-Type': 'application/json'}
        r = requests.post("{{workflow.parameters.issm_mec_cnmp_url}}//subnetslice",
            json={{inputs.parameters.data}}, headers=headers)
        json.dump(r.json(), sys.stdout)
        sys.stdout.write('\n')
        fiveg_subnet_id = r.json()['name']

        with open('/tmp/fiveg_subnet_id.txt', 'w') as f:
            f.write(str(fiveg_subnet_id))

    outputs:
      parameters:
      - name: fiveg_subnet_id
        valueFrom:
          path: /tmp/fiveg_subnet_id.txt
