apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: gitops-chn-ns
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  pathname: 'https://github.com/aviweit/ocp-git-sub-wf.git'
  type: GitHub
