# submit this from ACM
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: fiveg-core-acm
spec:
  entrypoint: handlerequest
  arguments:
    parameters:
    - name: registry
      value: "OVERRIDE"

    - name: cluster_core
      value: paris-core

  templates:
  - name: handlerequest
    dag:
      tasks:
      - name: create-core-subscription
        # TODO: wait on status
        template: create-core-subscription

  - name: create-core-subscription
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: apps.open-cluster-management.io/v1
        kind: Subscription
        metadata:
          annotations:
            apps.open-cluster-management.io/github-branch: multi-cluster-1
            apps.open-cluster-management.io/github-path: core-wf
          name: {{workflow.name}}
        spec:
          channel: gitops-chn-ns/gitops
          placement:
            clusters:
            - name: {{workflow.parameters.cluster_core}}
          packageOverrides:
          - packageName: fiveg-core
            packageOverrides:
            - path: metadata.name
              value: {{workflow.name}}
            - path: spec.arguments.parameters
              value:
              - name: registry
                value: {{workflow.parameters.registry}}

              - name: networks
                value: |
                  [
                    {
                      "name": "sbi",
                      "master": "ens3",
                      "range": "10.100.200.0/24",
                      "start": "10.100.200.2",
                      "end": "10.100.200.20"
                    },
                    {
                      "name": "ngap",
                      "master": "ens3",
                      "range": "192.168.1.0/24",
                      "start": "192.168.1.250",
                      "end": "192.168.1.250"
                    }
                  ]
        
