# Copyright 2021 - 2022 IBM Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# submit this from ACM
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fiveg-core-
spec:
  entrypoint: handlerequest
  arguments:
    parameters:
    - name: registry
      value: "OVERRIDE"

    - name: networks

    - name: cluster
      value: "OVERRIDE"

    - name: kafka_port
      value: 9092

  templates:
  - name: handlerequest
    dag:
      tasks:
      - name: create-core-subscription
        template: create-core-subscription

      - name: wait-for-core
        dependencies: [create-core-subscription]
        templateRef:
          name: workflow-base
          template: consume
        arguments:
          parameters:
          - name: kafka_ip
            value: "{{workflow.parameters.kafka_ip}}"
          - name: kafka_port
            value: "{{workflow.parameters.kafka_port}}"
          - name: kafka_topic
            value: "{{workflow.parameters.cluster}}"
          - name: msg_id
            value: "deploy-{{workflow.name}}"

  - name: create-core-subscription
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: apps.open-cluster-management.io/v1
        kind: Subscription
        metadata:
          annotations:
            apps.open-cluster-management.io/github-branch: multi-cluster-1
            apps.open-cluster-management.io/github-path: core-wf
          name: {{workflow.name}}
        spec:
          channel: gitops-chn-ns/gitops
          placement:
            clusters:
            - name: {{workflow.parameters.cluster}}
          packageOverrides:
          - packageName: fiveg-core
            packageOverrides:
            - path: metadata.name
              value: {{workflow.name}}
            - path: spec.arguments.parameters
              value:
              - name: registry
                value: {{workflow.parameters.registry}}

              - name: networks
                value: |
                  {{workflow.parameters.networks}}

              - name: msg_id
                value: "deploy-{{workflow.name}}"
