# Copyright 2021 - 2022 IBM Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# submit this from ACM
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fiveg-app-
spec:
  entrypoint: handlerequest
  arguments:
    parameters:
    - name: registry
      value: "OVERRIDE"

    - name: cluster

    - name: product_id
      value: "OVERRIDE"
    # issm-wfm sets this with stakeholder's elma
    - name: elma_url
      value: "OVERRIDE"

    # these are application specifics that load the proper CR operator to be
    # used as the VNFM
    - name: kind
    - name: api_version
    - name: success_condition

    - name: image
      value: "OVERRIDE"

    - name: network_name
      value: "OVERRIDE"

    - name: kafka_ip
      value: "OVERRIDE"
    - name: kafka_port
      value: 9092

  templates:
  - name: handlerequest
    dag:
      tasks:
      - name: create-app-subscription
        template: create-app-subscription

      - name: wait-for-app
        dependencies: [create-app-subscription]
        templateRef:
          name: workflow-base
          template: consume
        arguments:
          parameters:
          - name: kafka_ip
            value: "{{workflow.parameters.kafka_ip}}"
          - name: kafka_port
            value: "{{workflow.parameters.kafka_port}}"
          - name: kafka_topic
            value: "{{workflow.parameters.cluster}}"
          - name: msg_id
            value: "deploy-{{workflow.name}}"

  - name: create-app-subscription
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: apps.open-cluster-management.io/v1
        kind: Subscription
        metadata:
          annotations:
            apps.open-cluster-management.io/github-branch: multi-cluster-1
            apps.open-cluster-management.io/github-path: app-wf
          name: {{workflow.name}}
        spec:
          channel: gitops-chn-ns/gitops
          placement:
            clusters:
            - name: {{workflow.parameters.cluster}}
          packageOverrides:
          - packageName: fiveg-app
            packageOverrides:
            - path: metadata.name
              value: {{workflow.name}}
            - path: spec.arguments.parameters
              value:
              - name: registry
                value: {{workflow.parameters.registry}}

              - name: product_id
                value: "{{workflow.parameters.product_id}}"
              - name: elma_url
                value: "{{workflow.parameters.elma_url}}"

              - name: kind
                value: "{{workflow.parameters.kind}}"

              - name: api_version
                value: "{{workflow.parameters.api_version}}"

              - name: image
                value: "{{workflow.parameters.image}}"

              - name: kafka_ip
                value: "{{workflow.parameters.kafka_ip}}"
              - name: kafka_port
                value: "{{workflow.parameters.kafka_port}}"

              - name: topic
                value: "{{workflow.parameters.cluster}}"

              - name: msg_id
                value: "deploy-{{workflow.name}}"

              - name: fiveg_app_id
                value: "{{workflow.name}}"
