# This template runs on the target cluster
#
# This template get called out from fiveg-subnet-configure Workflow defined in
# gitops github pointed by the channel
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fiveg-subnet-configure
spec:
  templates:
  - name: handlerequest
    dag:
      tasks:
      - name: smf-add-node
        templateRef:
          name: nf-template
          template: create-tr
        arguments:
          parameters:
          - name: nf_apiversion
            value: "5g.ibm.com/v1alpha1"
          - name: nf_kind
            value: Transition
          - name: nf_name
            value: "smf-addnode-{{workflow.name}}"
          - name: nf_spec
            value: |
              {
                "config": {
                  "resourceType": "smfs.v1alpha1.5g.ibm.com",
                  "resourceNamespace": "{{workflow.namespace}}",
                  "resourceName": "{{workflow.parameters.smf_name}}",
                  "transition": "AttachNode",
                  "properties": {
                    # svc name or ip in sbi network
                    "nodeIdSbi": "{{workflow.parameters.upf_sbi}}",
                    # svc name or ip in up network
                    "nodeIdUp": "{{workflow.parameters.upf_up}}",
                    # for smf its a logical name of this upf to maintain map
                    # between it and its ip, slice id
                    "nodeName": "upf-{{workflow.name}}",
                    "nodeType": "UPF",
                    "sd": "{{workflow.parameters.sd}}",
                    "sst": "{{workflow.parameters.sst}}"
                  }
                }
              }

      - name: smf-add-link
        templateRef:
          name: nf-template
          template: create-tr
        arguments:
          parameters:
          - name: nf_apiversion
            value: "5g.ibm.com/v1alpha1"
          - name: nf_kind
            value: Transition
          - name: nf_name
            value: "smf-addlink-{{workflow.name}}"
          - name: nf_spec
            value: |
              {
                "config": {
                  "resourceType": "smfs.v1alpha1.5g.ibm.com",
                  "resourceNamespace": "{{workflow.namespace}}",
                  "resourceName": "{{workflow.parameters.smf_name}}",
                  "transition": "AddLink",
                  "properties": {
                    "nodeId": "gNB",
                    # for smf its a logical name of this upf to maintain map
                    # between it and its ip, slice id
                    "connectedTo": "upf-{{workflow.name}}"
                  }
                }
              }
