# Copyright 2021 - 2022 IBM Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This template runs on the target cluster
#
# This template get called out from fiveg-subnet-deploy Workflow defined in
# gitops github pointed by the channel
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fiveg-subnet-deploy
spec:
  templates:
  - name: handlerequest
    dag:
      tasks:
      - name: create-networks
        templateRef:
          name: network-template
          template: create-network
        arguments:
          parameters:
          - name: name
            value: "{{item.name}}"
          - name: master
            value: "{{item.master}}"
          - name: range
            value: "{{item.range}}"
          - name: start
            value: "{{item.start}}"
          - name: end
            value: "{{item.end}}"
        withParam: "{{workflow.parameters.networks}}"

      - name: create-datanetwork-and-upf
        when: "{{workflow.parameters.network_name}} != \"OVERRIDE\""
        template: create-datanetwork-and-upf

      - name: create-no-datanetwork-and-upf
        when: "{{workflow.parameters.network_name}} == \"OVERRIDE\""
        template: create-no-datanetwork-and-upf

      - name: read-upf-pod
        # a pod with same name is created for Upf CR
        dependencies: [create-no-datanetwork-and-upf, create-datanetwork-and-upf]
        templateRef:
          name: nf-template
          template: read-pod
        arguments:
          parameters:
          - name: pod_name
            value: upf-{{workflow.name}}


  - name: create-datanetwork-and-upf
    dag:
      tasks:
      - name: create-datanetwork
        templateRef:
          name: network-template
          template: create-network
        arguments:
          parameters:
          - name: name
            value: "{{workflow.parameters.network_name}}"
          - name: master
            value: "{{workflow.parameters.network_master}}"
          - name: range
            value: "{{workflow.parameters.network_range}}"
          - name: start
            value: "{{workflow.parameters.network_start}}"
          - name: end
            value: "{{workflow.parameters.network_end}}"

      - name: create-upf-on-datanetwork-pool
        when: "\"{{workflow.parameters.pool}}\" != \"0.0.0.0/16\""
        dependencies: [create-datanetwork]
        templateRef:
          name: nf-template
          template: create-nf
        arguments:
          parameters:
          - name: nf_apiversion
            value: "5g.ibm.com/v1alpha1"
          - name: nf_kind
            value: Upf
          - name: nf_name
            value: "upf-{{workflow.name}}"
          - name: success_condition
            value: "status.outputs.podname == upf-{{workflow.name}}"
          - name: nf_spec
            value: |
              {
                "config": {
                  "image": "{{workflow.parameters.registry}}/weit/free5gc-upf-tools:v3.0.6",
                  "image_init": "{{workflow.parameters.registry}}/weit/5ginitcontainer",
                  "upf_name": "upf-{{workflow.name}}",
                  "data_network_name": "{{workflow.parameters.network_name}}",
                  "dnns": [
                    {
                      "dnn_name": "internet",
                      apn_cidr: "{{workflow.parameters.pool}}"
                    }
                  ]
                }
              }

      - name: create-upf-on-datanetwork
        when: "\"{{workflow.parameters.pool}}\" == \"0.0.0.0/16\""
        dependencies: [create-datanetwork]
        templateRef:
          name: nf-template
          template: create-nf
        arguments:
          parameters:
          - name: nf_apiversion
            value: "5g.ibm.com/v1alpha1"
          - name: nf_kind
            value: Upf
          - name: nf_name
            value: "upf-{{workflow.name}}"
          - name: success_condition
            value: "status.outputs.podname == upf-{{workflow.name}}"
          - name: nf_spec
            value: |
              {
                "config": {
                  "image": "{{workflow.parameters.registry}}/weit/free5gc-upf-tools:v3.0.6",
                  "image_init": "{{workflow.parameters.registry}}/weit/5ginitcontainer",
                  "upf_name": "upf-{{workflow.name}}",
                  "data_network_name": "{{workflow.parameters.network_name}}"
                }
              }


  - name: create-no-datanetwork-and-upf
    dag:
      tasks:
      - name: create-upf-pool
        when: "\"{{workflow.parameters.pool}}\" != \"0.0.0.0/16\""
        templateRef:
          name: nf-template
          template: create-nf
        arguments:
          parameters:
          - name: nf_apiversion
            value: "5g.ibm.com/v1alpha1"
          - name: nf_kind
            value: Upf
          - name: nf_name
            value: "upf-{{workflow.name}}"
          - name: success_condition
            value: "status.outputs.podname == upf-{{workflow.name}}"            
          - name: nf_spec
            value: |
              {
                "config": {
                  "image": "{{workflow.parameters.registry}}/weit/free5gc-upf-tools:v3.0.6",
                  "image_init": "{{workflow.parameters.registry}}/weit/5ginitcontainer",
                  "upf_name": "upf-{{workflow.name}}",
                  "dnns": [
                    {
                      "dnn_name": "internet",
                      apn_cidr: "{{workflow.parameters.pool}}"
                    }
                  ]
                }
              }

      - name: create-upf
        when: "\"{{workflow.parameters.pool}}\" == \"0.0.0.0/16\""
        templateRef:
          name: nf-template
          template: create-nf
        arguments:
          parameters:
          - name: nf_apiversion
            value: "5g.ibm.com/v1alpha1"
          - name: nf_kind
            value: Upf
          - name: nf_name
            value: "upf-{{workflow.name}}"
          - name: success_condition
            value: "status.outputs.podname == upf-{{workflow.name}}"            
          - name: nf_spec
            value: |
              {
                "config": {
                  "image": "{{workflow.parameters.registry}}/weit/free5gc-upf-tools:v3.0.6",
                  "image_init": "{{workflow.parameters.registry}}/weit/5ginitcontainer",
                  "upf_name": "upf-{{workflow.name}}"
                }
              }
